import './style.css';

type E='金'|'木'|'水'|'火'|'土';
type K='normal'|'fast'|'tank'|'split'|'healer'|'elite'|'boss';
type Tower={id:number,e:E,x:number,y:number,damage:number,cooldown:number,range:number,damageMul:number,cooldownMul:number,rangeMul:number,statusMul:number,timer:number,level:number};
type PendingTower={id:number,e:E};
type Enemy={id:number,d:number,hp:number,maxHp:number,speed:number,e:E|null,k:K,leak:number,xp:number,alive:boolean,slow:number,slowTime:number,stun:number,poison:number,poisonTime:number,burn:number,burnTime:number};
const ELS:E[]=['金','木','水','火','土'];
const COLOR:Record<E,string>={金:'#f5c542',木:'#59c878',水:'#54b9ff',火:'#ff7043',土:'#c79a62'};
const ICON:Record<E,string>={金:'✦',木:'✣',水:'◈',火:'◆',土:'⬟'};
const NAME:Record<E,string>={金:'穿透',木:'毒蚀',水:'寒流',火:'爆炎',土:'重击'};
const EFFECT:Record<E,string>={金:'主目标后额外穿透2个目标。',木:'命中叠加毒素，持续造成伤害。',水:'命中减速敌人。',火:'命中产生范围爆炸并燃烧。',土:'高单次伤害，概率眩晕。'};
const COUNTER:Record<E,E>={金:'木',木:'土',土:'水',水:'火',火:'金'};
const BASE:Record<E,{damage:number,cooldown:number,range:number}>={金:{damage:25,cooldown:.62,range:125},木:{damage:11,cooldown:.78,range:130},水:{damage:10,cooldown:.72,range:145},火:{damage:24,cooldown:1.12,range:122},土:{damage:52,cooldown:1.75,range:112}};
const root=document.querySelector<HTMLDivElement>('#root')!;
root.innerHTML=`<div class="shell"><header class="topbar"><div class="brand"><span class="brand-mark">五</span><div><strong>FIVE ELEMENTS</strong><small>MAZE TD · PLAYTEST</small></div></div><div class="stats"><div><span>TIME</span><b id="time">00:00</b></div><div><span>LEVEL</span><b id="level">Lv.1</b></div><div><span>XP</span><b id="xp">0</b></div><div class="leak"><span>LEAK</span><b id="leak">0 / 20</b></div></div></header><main class="stage"><div class="game-wrap"><canvas id="game"></canvas><div id="towerInspector" class="tower-inspector hidden"></div><div id="toast" class="toast hidden"></div></div><aside class="sidepanel"><section class="panel"><div class="panel-title">BUILD · 待放置塔</div><div id="build" class="build"></div></section><section class="panel"><div class="panel-title">RUN</div><div id="runInfo" class="wave"></div></section><section class="panel debug"><div class="panel-title">PLAYTEST</div><div id="debug">Loading…</div><div class="debug-buttons"><button id="debugXp">+100 XP</button><button id="debugBoss">Boss</button><button id="debugClear">Clear</button></div></section></aside></main></div><div id="levelup" class="overlay hidden"><div class="card-modal"><div class="modal-kicker" id="modalKicker">LEVEL UP</div><h2 id="modalTitle">Choose</h2><div id="choices" class="choices"></div></div></div>`;
const canvas=document.querySelector<HTMLCanvasElement>('#game')!;const ctx=canvas.getContext('2d')!;
let W=900,H=700,running=false,ended=false,time=0,xp=0,level=1,leak=0,enemyId=0,towerId=0,spawn=0,totalDamage=0,boss:Enemy|null=null,pendingLevels=0,selected:Tower|null=null,activePlacementId:number|null=null,dragging:Tower|null=null,dragX=0,dragY=0,dragValid=false,dragMoved=false;
const towers:Tower[]=[];const pendingTowers:PendingTower[]=[];const enemies:Enemy[]=[];const unlocked=new Set<E>();const upgrades:Record<E,number>={金:0,木:0,水:0,火:0,土:0};
const path=[{x:45,y:55},{x:180,y:55},{x:180,y:145},{x:345,y:145},{x:345,y:65},{x:575,y:65},{x:575,y:180},{x:790,y:180},{x:790,y:305},{x:635,y:305},{x:635,y:420},{x:825,y:420},{x:825,y:555},{x:600,y:555},{x:600,y:630},{x:370,y:630},{x:370,y:520},{x:145,y:520},{x:145,y:400},{x:305,y:400},{x:305,y:285},{x:90,y:285},{x:90,y:205},{x:45,y:205},{x:45,y:55}];
const ROAD=54;let lens=[0],totalPath=0;for(let i=1;i<path.length;i++){totalPath+=Math.hypot(path[i].x-path[i-1].x,path[i].y-path[i-1].y);lens.push(totalPath);}
function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);W=r.width;H=r.height;canvas.width=W*d;canvas.height=H*d;ctx.setTransform(d,0,0,d,0,0)}addEventListener('resize',resize);resize();
function pos(dist:number){dist=Math.max(0,Math.min(totalPath,dist));let i=1;while(i<lens.length&&lens[i]<dist)i++;const a=path[i-1],b=path[i],s=lens[i]-lens[i-1],q=s?(dist-lens[i-1])/s:0;return{x:a.x+(b.x-a.x)*q,y:a.y+(b.y-a.y)*q}}
function segDist(px:number,py:number,a:{x:number,y:number},b:{x:number,y:number}){const dx=b.x-a.x,dy=b.y-a.y,l=dx*dx+dy*dy;if(!l)return Math.hypot(px-a.x,py-a.y);const q=Math.max(0,Math.min(1,((px-a.x)*dx+(py-a.y)*dy)/l));return Math.hypot(px-(a.x+q*dx),py-(a.y+q*dy))}
function pathDist(x:number,y:number){let d=Infinity;for(let i=1;i<path.length;i++)d=Math.min(d,segDist(x,y,path[i-1],path[i]));return d}
function canPlace(x:number,y:number,ignore:Tower|null=null){if(x<35||x>865||y<35||y>665)return false;if(pathDist(x,y)<ROAD/2+27)return false;return !towers.some(t=>t!==ignore&&Math.hypot(t.x-x,t.y-y)<52)}
function stats(t:Tower){return{damage:t.damage*t.damageMul,cooldown:t.cooldown*t.cooldownMul,range:t.range*t.rangeMul,dps:t.damage*t.damageMul/(t.cooldown*t.cooldownMul)}}
function relation(a:E,b:E|null){if(!b)return 1;if(COUNTER[a]===b)return 1.3;if(COUNTER[b]===a)return .7;return 1}
function toast(s:string){const el=document.querySelector<HTMLDivElement>('#toast')!;el.textContent=s;el.classList.remove('hidden');clearTimeout(Number(el.dataset.t));el.dataset.t=String(setTimeout(()=>el.classList.add('hidden'),1800))}
function obtainTower(e:E){unlocked.add(e);const p:PendingTower={id:++towerId,e};pendingTowers.push(p);return p}
function placePending(id:number,x:number,y:number){const p=pendingTowers.find(v=>v.id===id);if(!p||!canPlace(x,y))return false;const b=BASE[p.e];towers.push({id:p.id,e:p.e,x,y,damage:b.damage,cooldown:b.cooldown,range:b.range,damageMul:1,cooldownMul:1,rangeMul:1,statusMul:1,timer:.05,level:1});const i=pendingTowers.findIndex(v=>v.id===id);pendingTowers.splice(i,1);activePlacementId=null;toast(`${p.e}塔已放置`);return true}
function buildUi(){const el=document.querySelector<HTMLDivElement>('#build')!;el.innerHTML=pendingTowers.map(p=>`<button class="tower-row" data-pending-id="${p.id}" aria-pressed="${activePlacementId===p.id}"><i style="background:${COLOR[p.e]}">${ICON[p.e]}</i><span>${p.e} · ${NAME[p.e]}<small>${activePlacementId===p.id?' · 已选择，点击地图放置':' · 点击选择，可随时放置'}</small></span></button>`).join('')||'<div class="muted">暂无待放置塔</div>'}
document.querySelector<HTMLDivElement>('#build')!.addEventListener('click',ev=>{const b=(ev.target as HTMLElement).closest<HTMLButtonElement>('[data-pending-id]');if(!b)return;ev.preventDefault();ev.stopPropagation();const id=Number(b.dataset.pendingId);if(!pendingTowers.some(p=>p.id===id))return;activePlacementId=id;selected=null;toast(`已选择 ${pendingTowers.find(p=>p.id===id)!.e}塔，请点击地图空地`);ui()});
function inspector(){const el=document.querySelector<HTMLDivElement>('#towerInspector')!;if(!selected){el.classList.add('hidden');return}const s=stats(selected);el.classList.remove('hidden');el.innerHTML=`<div class="tower-inspector-head"><div class="tower-inspector-icon" style="background:${COLOR[selected.e]}">${ICON[selected.e]}</div><div><strong>${selected.e}塔 · ${NAME[selected.e]}</strong><small>等级 ${selected.level} · 强化 ${upgrades[selected.e]} 次</small></div><button id="closeTower" type="button">×</button></div><div class="tower-range-label">实际攻击范围 <b>${s.range.toFixed(0)}</b></div><div class="tower-stat-grid"><div><span>伤害</span><b>${s.damage.toFixed(1)}</b></div><div><span>攻击间隔</span><b>${s.cooldown.toFixed(2)}s</b></div><div><span>攻速</span><b>${(1/s.cooldown).toFixed(2)}/s</b></div><div><span>实际DPS</span><b>${s.dps.toFixed(1)}</b></div><div><span>状态强度</span><b>${(selected.statusMul*100).toFixed(0)}%</b></div><div><span>克制倍率</span><b>×1.30 / ×0.70</b></div></div><div class="tower-effect"><span>核心效果</span><strong>${EFFECT[selected.e]}</strong></div><div class="tower-relation">克制 ${COUNTER[selected.e]} ×1.30 · 被 ${ELS.find(x=>COUNTER[x]===selected!.e)} 克制 ×0.70</div>`;el.querySelector<HTMLButtonElement>('#closeTower')!.onclick=()=>{selected=null;inspector()}}
function ui(){const m=String(Math.floor(time/60)).padStart(2,'0'),s=String(Math.floor(time%60)).padStart(2,'0');document.querySelector('#time')!.textContent=`${m}:${s}`;document.querySelector('#level')!.textContent=`Lv.${level}`;document.querySelector('#xp')!.textContent=`${Math.round(xp)}`;document.querySelector('#leak')!.textContent=`${leak} / 20`;buildUi();document.querySelector('#runInfo')!.innerHTML=`${boss?'BOSS FIGHT':'MAZE SURVIVAL'}<br>已放置 ${towers.length} · 待放置 ${pendingTowers.length}<br>${activePlacementId?`已选择塔 #${activePlacementId} · 点击地图放置`:'点击任意待放置塔卡片即可选择'}`;document.querySelector('#debug')!.innerHTML=`敌人 ${enemies.filter(e=>e.alive).length}<br>总伤害 ${Math.round(totalDamage)}<br>Boss ${boss?`${Math.max(0,Math.round(boss.hp))}/${Math.round(boss.maxHp)}`:'—'}`;inspector()}
function applyHit(e:Enemy,t:Tower,raw:number){if(!e.alive)return;const amount=raw*relation(t.e,e.e);e.hp-=amount;totalDamage+=amount;if(t.e==='木'){e.poison=Math.min(e.poison+raw*.2*t.statusMul,raw*1.25);e.poisonTime=3.2}if(t.e==='水'){e.slow=.62;e.slowTime=Math.max(e.slowTime,1.8*t.statusMul)}if(t.e==='火'){e.burn=Math.max(e.burn,raw*.18*t.statusMul);e.burnTime=3}if(t.e==='土'&&Math.random()<Math.min(.34*t.statusMul,.8))e.stun=Math.max(e.stun,.7*t.statusMul);if(e.hp<=0)kill(e)}
function target(t:Tower){let best:Enemy|null=null,bd=-1;for(const e of enemies)if(e.alive&&e.d<totalPath&&inRange(t,e)&&e.d>bd){best=e;bd=e.d}return best}
function inRange(t:Tower,e:Enemy){const p=pos(e.d);return Math.hypot(p.x-t.x,p.y-t.y)<=stats(t).range}
function fire(t:Tower){const e=target(t);if(!e)return;const s=stats(t);applyHit(e,t,s.damage);if(t.e==='金')enemies.filter(o=>o.alive&&o!==e&&inRange(t,o)).sort((a,b)=>b.d-a.d).slice(0,2).forEach((o,i)=>applyHit(o,t,s.damage*(i?.42:.65)));if(t.e==='火'){const p=pos(e.d);for(const o of enemies)if(o.alive&&o!==e){const q=pos(o.d);if(Math.hypot(p.x-q.x,p.y-q.y)<48)applyHit(o,t,s.damage*.48)}}}
function kill(e:Enemy){if(!e.alive)return;e.alive=false;xp+=e.xp;if(e.k==='split'){spawnEnemy('normal',e.e);spawnEnemy('normal',e.e)}checkLevel()}
function spawnEnemy(k:K='normal',force:E|null=null){const p=Math.min(time/270,1),base=42+260*Math.pow(p,1.65);const D={normal:[base,31+p*11,5,1],fast:[base*.68,(31+p*11)*1.7,6,1],tank:[base*3.1,(31+p*11)*.62,9,1],split:[base*1.55,(31+p*11)*.9,8,1],healer:[base*1.4,(31+p*11)*.82,10,1],elite:[base*5.4,(31+p*11)*.76,45,3],boss:[1,11,0,20]}[k];const e=force??(Math.random()<Math.min(.22+time/360,.82)?ELS[Math.floor(Math.random()*5)]:null);enemies.push({id:++enemyId,d:0,hp:D[0],maxHp:D[0],speed:D[1],e,k,leak:D[3],xp:D[2],alive:true,slow:1,slowTime:0,stun:0,poison:0,poisonTime:0,burn:0,burnTime:0})}
function updateEnemy(e:Enemy,dt:number){if(!e.alive)return;if(e.poisonTime>0){e.hp-=e.poison*dt;e.poisonTime-=dt;if(e.hp<=0){kill(e);return}}if(e.burnTime>0){e.hp-=e.burn*dt;e.burnTime-=dt;if(e.hp<=0){kill(e);return}}if(e.k==='healer')for(const o of enemies)if(o!==e&&o.alive&&Math.hypot(pos(o.d).x-pos(e.d).x,pos(o.d).y-pos(e.d).y)<70)o.hp=Math.min(o.maxHp,o.hp+o.maxHp*.012*dt);if(e.stun>0){e.stun-=dt;return}if(e.slowTime>0)e.slowTime-=dt;else e.slow=1;e.d+=e.speed*e.slow*dt;if(e.d>=totalPath){e.alive=false;leak+=e.leak;if(leak>=20)end(false)}}
function wave(dt:number){if(time>=270||boss)return;spawn+=dt;const iv=time<60?1.55:time<120?1.18:time<180?.9:time<240?.72:.58;if(spawn<iv)return;spawn=0;const r=Math.random();let k:K='normal';if(time>95&&r<.13)k='fast';else if(time>125&&r<.25)k='tank';else if(time>145&&r<.34)k='split';else if(time>170&&r<.42)k='healer';else if(time>115&&r<.49)k='elite';spawnEnemy(k)}
function bossStart(){if(boss)return;const dps=Math.max(90,totalDamage/Math.max(time,1));const hp=dps*30+900;boss={id:++enemyId,d:0,hp,maxHp:hp,speed:11,e:ELS[Math.floor(Math.random()*5)],k:'boss',leak:20,xp:0,alive:true,slow:1,slowTime:0,stun:0,poison:0,poisonTime:0,burn:0,burnTime:0};enemies.push(boss);toast(`BOSS · ${boss.e}属性`)}
function checkLevel(){const need=[0,22,50,85,125,175,235,305,385,475,575,685,805,935,1075,1225,1385,1555,1735,1925];while(level<20&&xp>=need[level]){level++;pendingLevels++}if(pendingLevels&&running)showLevel()}
function showLevel(){running=false;const ov=document.querySelector<HTMLDivElement>('#levelup')!,ch=document.querySelector<HTMLDivElement>('#choices')!;ch.innerHTML='';const newTower=[6,11,15].includes(level)&&unlocked.size<5;if(newTower){document.querySelector('#modalKicker')!.textContent=`LEVEL ${level} · NEW TOWER`;document.querySelector('#modalTitle')!.textContent='选择新的五行塔';ELS.filter(e=>!unlocked.has(e)).sort(()=>Math.random()-.5).slice(0,3).forEach(e=>{const b=document.createElement('button');b.className='choice element-choice';b.style.borderColor=COLOR[e];b.innerHTML=`<small style="color:${COLOR[e]}">新塔</small><strong>${ICON[e]} ${e} · ${NAME[e]}</strong><span>${EFFECT[e]}<br>获得后进入右侧待放置卡片</span>`;b.onclick=()=>{obtainTower(e);pendingLevels--;ov.classList.add('hidden');if(pendingLevels)showLevel();else running=true;ui()};ch.appendChild(b)})}else{document.querySelector('#modalKicker')!.textContent=`LEVEL ${level}`;document.querySelector('#modalTitle')!.textContent='选择一座塔强化';ELS.filter(e=>unlocked.has(e)).sort(()=>Math.random()-.5).slice(0,3).forEach(e=>{const b=document.createElement('button');b.className='choice';b.style.borderColor=COLOR[e];b.innerHTML=`<small style="color:${COLOR[e]}">${e} · ${NAME[e]}</small><strong>强化 ${EFFECT[e]}</strong><span>强化场上全部 ${e}塔</span>`;b.onclick=()=>{towers.filter(t=>t.e===e).forEach(t=>{t.damageMul*=1.12;t.rangeMul*=1.08;t.cooldownMul*=.92;t.statusMul*=1.08;t.level++});upgrades[e]++;pendingLevels--;ov.classList.add('hidden');if(pendingLevels)showLevel();else running=true;ui()};ch.appendChild(b)})}ov.classList.remove('hidden')}
function first(){running=false;const ov=document.querySelector<HTMLDivElement>('#levelup')!,ch=document.querySelector<HTMLDivElement>('#choices')!;ch.innerHTML='';document.querySelector('#modalKicker')!.textContent='START';document.querySelector('#modalTitle')!.textContent='选择第一座塔';ELS.sort(()=>Math.random()-.5).slice(0,3).forEach(e=>{const b=document.createElement('button');b.className='choice element-choice';b.style.borderColor=COLOR[e];b.innerHTML=`<small style="color:${COLOR[e]}">元素塔</small><strong>${ICON[e]} ${e} · ${NAME[e]}</strong><span>${EFFECT[e]}<br>获得后进入右侧待放置卡片</span>`;b.onclick=()=>{obtainTower(e);ov.classList.add('hidden');running=true;toast(`已获得 ${e}塔，请点击右侧卡片后在地图放置`);ui()};ch.appendChild(b)});ov.classList.remove('hidden')}
function end(win:boolean){ended=true;running=false;const ov=document.querySelector<HTMLDivElement>('#levelup')!;document.querySelector('#modalKicker')!.textContent='RUN COMPLETE';document.querySelector('#modalTitle')!.textContent=win?'VICTORY':'DEFEAT';document.querySelector('#choices')!.innerHTML=`<div class="result">${win?'Boss defeated.':'20 leaks reached.'}<br>等级 Lv.${level} · 总伤害 ${Math.round(totalDamage)}<br><button id="restart">PLAY AGAIN</button></div>`;document.querySelector<HTMLButtonElement>('#restart')!.onclick=()=>location.reload();ov.classList.remove('hidden')}
function pointerPoint(ev:PointerEvent){const r=canvas.getBoundingClientRect();return{x:(ev.clientX-r.left)/r.width*900,y:(ev.clientY-r.top)/r.height*700}}
function towerAt(x:number,y:number){let hit:Tower|null=null,b=Infinity;for(const t of towers){const d=Math.hypot(t.x-x,t.y-y);if(d<30&&d<b){hit=t;b=d}}return hit}
canvas.addEventListener('pointerdown',ev=>{if(ended)return;const {x,y}=pointerPoint(ev);const hit=towerAt(x,y);if(hit){selected=hit;activePlacementId=null;dragging=hit;dragX=x;dragY=y;dragValid=true;dragMoved=false;canvas.setPointerCapture?.(ev.pointerId);ui();return}selected=null;if(activePlacementId!==null&&running){if(placePending(activePlacementId,x,y))ui();else toast('这里不能放塔：道路、边界或距离已有塔太近');elseClear()} });
function elseClear(){if(activePlacementId!==null&&pendingTowers.length===0)activePlacementId=null}
canvas.addEventListener('pointermove',ev=>{if(!dragging)return;const {x,y}=pointerPoint(ev);if(Math.hypot(x-dragX,y-dragY)>4)dragMoved=true;dragX=x;dragY=y;dragValid=canPlace(x,y,dragging);if(dragMoved)ui()});
canvas.addEventListener('pointerup',ev=>{if(!dragging)return;const t=dragging;dragging=null;if(dragMoved&&dragValid){t.x=dragX;t.y=dragY;toast(`${t.e}塔已移动`)}else if(dragMoved&&!dragValid)toast('位置无效，塔保持原位');selected=t;ui();canvas.releasePointerCapture?.(ev.pointerId)});
canvas.addEventListener('pointercancel',()=>{dragging=null;dragMoved=false;ui()});
document.querySelector('#debugXp')!.addEventListener('click',()=>{xp+=100;checkLevel();ui()});document.querySelector('#debugBoss')!.addEventListener('click',()=>{bossStart();ui()});document.querySelector('#debugClear')!.addEventListener('click',()=>enemies.forEach(e=>e.alive=false));
function update(dt:number){if(!running||ended)return;time+=dt;if(time>=270&&!boss)bossStart();wave(dt);for(const e of enemies)updateEnemy(e,dt);for(const t of towers){t.timer-=dt;if(t.timer<=0){fire(t);t.timer+=stats(t).cooldown}}if(boss&&!boss.alive)end(true);ui()}
function draw(){const sx=W/900,sy=H/700;ctx.save();ctx.scale(sx,sy);ctx.clearRect(0,0,900,700);const g=ctx.createLinearGradient(0,0,900,700);g.addColorStop(0,'#12243a');g.addColorStop(1,'#07101c');ctx.fillStyle=g;ctx.fillRect(0,0,900,700);ctx.fillStyle='#0b1522';ctx.fillRect(15,15,870,670);ctx.strokeStyle='rgba(140,180,210,.05)';ctx.lineWidth=1;for(let x=30;x<880;x+=35){ctx.beginPath();ctx.moveTo(x,20);ctx.lineTo(x,680);ctx.stroke()}for(let y=30;y<680;y+=35){ctx.beginPath();ctx.moveTo(20,y);ctx.lineTo(880,y);ctx.stroke()}ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle='#172936';ctx.lineWidth=ROAD+12;ctx.beginPath();ctx.moveTo(path[0].x,path[0].y);path.slice(1).forEach(p=>ctx.lineTo(p.x,p.y));ctx.stroke();ctx.strokeStyle='#566b58';ctx.lineWidth=ROAD;ctx.beginPath();ctx.moveTo(path[0].x,path[0].y);path.slice(1).forEach(p=>ctx.lineTo(p.x,p.y));ctx.stroke();ctx.strokeStyle='rgba(255,255,255,.08)';ctx.lineWidth=2;ctx.setLineDash([9,10]);ctx.beginPath();ctx.moveTo(path[0].x,path[0].y);path.slice(1).forEach(p=>ctx.lineTo(p.x,p.y));ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#59c878';ctx.beginPath();ctx.arc(path[0].x,path[0].y,13,0,Math.PI*2);ctx.fill();const out=path[path.length-1];ctx.fillStyle='#ff6464';ctx.beginPath();ctx.arc(out.x,out.y,13,0,Math.PI*2);ctx.fill();ctx.fillStyle='#c8d5df';ctx.font='900 11px system-ui';ctx.textAlign='center';ctx.fillText('IN',path[0].x,path[0].y-20);ctx.fillText('OUT',out.x,out.y-20);
if(activePlacementId!==null){const p=pendingTowers.find(v=>v.id===activePlacementId);if(p){ctx.fillStyle=`${COLOR[p.e]}12`;ctx.fillRect(20,20,860,660);ctx.fillStyle=COLOR[p.e];ctx.font='800 13px system-ui';ctx.fillText(`放置 ${p.e}塔 · 点击道路外的空地`,450,32)}}
if(dragging){ctx.beginPath();ctx.arc(dragX,dragY,stats(dragging).range,0,Math.PI*2);ctx.fillStyle=dragValid?`${COLOR[dragging.e]}18`:'rgba(255,80,80,.16)';ctx.fill();ctx.strokeStyle=dragValid?COLOR[dragging.e]:'#ff5c5c';ctx.lineWidth=2;ctx.setLineDash([8,6]);ctx.stroke();ctx.setLineDash([])}if(selected&&!dragging){const s=stats(selected);ctx.beginPath();ctx.arc(selected.x,selected.y,s.range,0,Math.PI*2);ctx.fillStyle=`${COLOR[selected.e]}18`;ctx.fill();ctx.strokeStyle=COLOR[selected.e];ctx.lineWidth=2;ctx.setLineDash([8,6]);ctx.stroke();ctx.setLineDash([])}for(const t of towers){if(dragging===t)continue;const c=COLOR[t.e];ctx.fillStyle=c;ctx.shadowColor=c;ctx.shadowBlur=selected===t?25:12;ctx.beginPath();ctx.arc(t.x,t.y,21,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#08111d';ctx.font='900 17px system-ui';ctx.textAlign='center';ctx.fillText(ICON[t.e],t.x,t.y+6);if(t.level>1){ctx.fillStyle='#fff';ctx.font='700 8px system-ui';ctx.fillText(`Lv${t.level}`,t.x,t.y+32)}}for(const e of enemies){if(!e.alive)continue;const p=pos(e.d),c=e.e?COLOR[e.e]:'#b8c4d1',r=e.k==='boss'?29:e.k==='elite'?14:e.k==='tank'?12:8;ctx.fillStyle=c;ctx.shadowColor=c;ctx.shadowBlur=e.k==='boss'?28:7;ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='rgba(0,0,0,.55)';ctx.fillRect(p.x-16,p.y-r-9,32,4);ctx.fillStyle='#7fe29b';ctx.fillRect(p.x-16,p.y-r-9,32*Math.max(0,e.hp/e.maxHp),4)}if(boss?.alive){ctx.fillStyle='#fff';ctx.font='900 12px system-ui';ctx.fillText(`${boss.e} BOSS`,450,47);ctx.fillStyle='rgba(0,0,0,.6)';ctx.fillRect(250,57,400,8);ctx.fillStyle=COLOR[boss.e!];ctx.fillRect(250,57,400*Math.max(0,boss.hp/boss.maxHp),8)}ctx.restore()}
let last=performance.now();function loop(now:number){const dt=Math.min((now-last)/1000,.05);last=now;update(dt);draw();requestAnimationFrame(loop)}
first();requestAnimationFrame(loop);

// Test/debug API: deterministic creation of independent pending instances.
(window as Window & {__fiveElementsTest?:unknown}).__fiveElementsTest={reset:()=>{pendingTowers.splice(0);towers.splice(0);activePlacementId=null;selected=null},addPending:(elements:E[])=>elements.map(obtainTower),pendingIds:()=>pendingTowers.map(p=>p.id),selectPending:(id:number)=>{if(!pendingTowers.some(p=>p.id===id))return false;activePlacementId=id;ui();return true},placePending:(id:number,x:number,y:number)=>placePending(id,x,y)};
